// Generated by CoffeeScript 1.3.1
(function() {
  var ApplicationCache,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  ApplicationCache = (function() {

    ApplicationCache.name = 'ApplicationCache';

    function ApplicationCache() {
      this.remove = __bind(this.remove, this);

      this.add = __bind(this.add, this);
      this.items = {};
    }

    ApplicationCache.prototype.add = function(key, value) {
      return this.items[key] = value;
    };

    ApplicationCache.prototype.remove = function(key) {
      return delete this.items[key];
    };

    return ApplicationCache;

  })();

  exports.ApplicationCache = ApplicationCache;

}).call(this);
