// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Database, Mongo, utils;

  Mongo = require('mongodb');

  utils = require('./utils');

  Database = (function() {

    Database.name = 'Database';

    function Database(conf) {
      this.conf = conf;
    }

    Database.prototype.getDb = function() {
      return new Mongo.Db(this.conf.name, new Mongo.Server(this.conf.host, this.conf.port, {}), {});
    };

    Database.prototype.execute = function(task) {
      var db;
      db = this.getDb();
      return db.open(function(err, db) {
        try {
          return task(db, function(err) {});
        } catch (e) {
          return utils.dumpError(e);
        }
      });
    };

    Database.prototype.insert = function(collectionName, document, cb) {
      return this.execute(function(db, completionCB) {
        return db.collection(collectionName, function(err, collection) {
          return collection.insert(document, {
            safe: true
          }, function(e, r) {
            cb(e, r[0]);
            return completionCB(e);
          });
        });
      });
    };

    Database.prototype.update = function(collectionName, document, cb) {
      return this.execute(function(db, completionCB) {
        return db.collection(collectionName, function(err, collection) {
          return collection.update({
            _id: document._id
          }, document, {
            safe: true
          }, function(e, r) {
            cb(e, r);
            return completionCB(e);
          });
        });
      });
    };

    Database.prototype.updateMany = function(collectionName, params, document, cb) {
      return this.execute(function(db, completionCB) {
        return db.collection(collectionName, function(err, collection) {
          return collection.update(params, document, {
            safe: true,
            multi: true
          }, function(e, r) {
            cb(e, r);
            return completionCB(e);
          });
        });
      });
    };

    Database.prototype.find = function(collectionName, query, cb) {
      return this.execute(function(db, completionCB) {
        return db.collection(collectionName, function(err, collection) {
          var cursor;
          cursor = collection.find(query);
          cb(err, cursor);
          return completionCB(err);
        });
      });
    };

    Database.prototype.findOne = function(collectionName, query, cb) {
      return this.find(collectionName, query, function(err, cursor) {
        return cursor.nextObject(function(err, item) {
          return cb(err, item);
        });
      });
    };

    Database.prototype.remove = function(collection, document, cb) {
      return this.execute(function(db, completionCB) {
        return db.collection(collectionName, function(err, collection) {
          return collection.remove({
            _id: document._id
          }, {
            safe: true
          }, function(e, r) {
            cb(e, r);
            return completionCB(e);
          });
        });
      });
    };

    Database.prototype.ObjectId = function(id) {
      if (typeof id === "string") {
        return new Mongo.BSONPure.ObjectID(id);
      } else {
        return id;
      }
    };

    return Database;

  })();

  exports.Database = Database;

}).call(this);
