// Generated by CoffeeScript 1.3.1
(function() {
  var Exception,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Exception = (function() {

    Exception.name = 'Exception';

    function Exception(type, message) {
      this.type = type;
      this.message = message;
      this.toString = __bind(this.toString, this);

    }

    Exception.prototype.toString = function() {
      return "" + this.type + ", " + this.message;
    };

    return Exception;

  })();

  exports.Exception = Exception;

}).call(this);
