// Generated by CoffeeScript 1.2.1-pre
(function() {
  var localhost;

  localhost = '127.0.0.1';

  module.exports = {
    database: {
      name: 'typistdb',
      host: localhost,
      port: 27017
    }
  };

}).call(this);
