// Generated by CoffeeScript 1.2.1-pre
(function() {
  var Controller;

  Controller = (function() {

    Controller.name = 'Controller';

    function Controller() {}

    Controller.prototype.getLoginStatus = function(req) {
      var status, _ref;
      if ((_ref = req.session.user) != null ? _ref.username : void 0) {
        status = {
          loggedIn: true,
          js: "window.authProvider = '" + req.session.authProvider + "'; window.loggedIn = true; window.username = '" + req.session.user.username + "';",
          header: "<a class=\"logoutLink\" href=\"#\">Logout</a> <span class=\"username\">" + req.session.user.username + "</span>"
        };
      } else {
        status = {
          loggedIn: false,
          js: "window.loggedIn = false; window.username = null;",
          header: '<img src="/public/images/facebook.png" /><a class="fbLoginLink" href="#">Login</a>'
        };
      }
      return status;
    };

    Controller.prototype.ensureSession = function(fn) {
      return function(req, res, next) {
        if (req.session.user != null) {
          return fn(req, res, next);
        } else {
          return res.redirect('/login');
        }
      };
    };

    Controller.prototype.getUserId = function(req) {
      var _ref;
      if ((_ref = req.session.user) != null ? _ref.username : void 0) {
        return req.session.user._id.toString();
      } else {
        throw {
          type: 'NOT_LOGGED_IN'
        };
      }
    };

    return Controller;

  })();

  exports.Controller = Controller;

}).call(this);
