// Generated by CoffeeScript 1.3.1
(function() {
  var adminController, controller, homeController, storiesController;

  controller = require('./controller');

  homeController = require('./homecontroller');

  storiesController = require('./storiescontroller');

  adminController = require('./admincontroller');

  exports.Controller = controller.Controller;

  exports.HomeController = homeController.HomeController;

  exports.StoriesController = storiesController.StoriesController;

  exports.AdminController = adminController.AdminController;

}).call(this);
