// Generated by CoffeeScript 1.2.1-pre
(function() {
  var controller, homeController, storiesController;

  controller = require('./controller');

  homeController = require('./homecontroller');

  storiesController = require('./storiescontroller');

  exports.Controller = controller.Controller;

  exports.HomeController = homeController.HomeController;

  exports.StoriesController = storiesController.StoriesController;

}).call(this);
