// Generated by CoffeeScript 1.2.1-pre
(function() {

  module.exports = {
    "default": {
      name: 'typistdb',
      host: '127.0.0.1',
      port: 27017
    },
    sessions: {
      name: 'typistsessions',
      host: '127.0.0.1',
      port: 27017
    }
  };

}).call(this);
