// Generated by CoffeeScript 1.2.1-pre
(function() {
  var BaseModel, Message,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BaseModel = require('./basemodel').BaseModel;

  Message = (function(_super) {

    __extends(Message, _super);

    Message.name = 'Message';

    function Message() {
      return Message.__super__.constructor.apply(this, arguments);
    }

    Message._meta = {
      type: Message,
      collection: 'messages'
    };

    return Message;

  })(BaseModel);

  exports.Message = Message;

}).call(this);
