// Generated by CoffeeScript 1.3.1
(function() {
  var BaseModel, StoryChange,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BaseModel = require('./basemodel').BaseModel;

  StoryChange = (function(_super) {

    __extends(StoryChange, _super);

    StoryChange.name = 'StoryChange';

    function StoryChange() {
      return StoryChange.__super__.constructor.apply(this, arguments);
    }

    StoryChange._meta = {
      type: StoryChange,
      collection: 'storychanges'
    };

    return StoryChange;

  })(BaseModel);

  exports.StoryChange = StoryChange;

}).call(this);
